channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - tensorflow-base
  - pytorch
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - requests
  - dask
  - jupyter
  - jupyterlab
  - pip:
      - ray[tune]
      - gym
      - gymnasium
      - numpy==1.19.5  # Ensure numpy is not upgraded