name: autockt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.16.4
  - scipy=1.1.0
  - opencv=3.4.2
  - matplotlib=3.0.0
  - pip
  - pip:
      - tensorflow==1.10.1
      - gym==0.10.5
      - ray==0.6.3
      - requests==2.22.0
      - protobuf==3.9.2
