name: autockt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6  # Closest stable version to 3.5, since 3.5 is no longer available
  - scipy=1.1.0
  - opencv=3.4.2
  - matplotlib=3.0.0
  - numpy=1.16.4
  - pip
  - pip:
      - tensorflow==1.10.1
      - gym==0.10.5
      - protobuf==3.9.2
      - ray==0.6.3
      - requests==2.22.0
      - absl-py==0.8.0
      - astor==0.8.0
      - grpcio==1.24.0
      - markdown==3.1.1
      - pyyaml==5.1.2
      - redis==3.3.8
      - setuptools==39.1.0
      - six==1.12.0
      - tensorboard==1.10.0
      - termcolor==1.1.0
      - urllib3==1.25.6
